Ramazanov
avalon-dev-j30/lab-1-ramazanovmax pull request #1
Opened 2019-06-01 07:28 UTC by ramazanovmax

Лаб 1

2019-06-02 11:20 UTC, konivex requested changes
Исправьте замечания.

2019-06-02 11:20 UTC, konivex commented on src/ru/avalon/java/j30/labs/script.sql
> +               constraint ck_role_id check ( id < 10000000000 and id > 0)
Максимальное значение, которое может иметь колонка типа integer, -- это 2_147_483_647, так что условие "id < 10_000_000_000" истинным будет всегда. Оно здесь лишнее.
Это замечание касается всех аналогичных условий ниже.

2019-06-02 11:20 UTC, konivex commented on src/ru/avalon/java/j30/labs/script.sql
> +                    constraint fk_user_userinfo_id  foreign key (info) references userinfo(id),
Ваши check constraint'ы на колонки, составляющие внешний ключ, бессмысленны, т.к. значения таких колонок ограничены набором значений соответствующей колонки в той таблице, на которую ключ ссылается.
Это замечание касается аналогичных constraint'ов ниже.

2019-06-05 20:45 UTC, ramazanovmax commented
Исправил замечания

2019-06-05 21:42 UTC, merged

2019-06-06 15:05 UTC, konivex reviewed
Зачтено.